//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZXWebApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_Mesin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tm_Mesin()
        {
            this.tt_Transaction = new HashSet<tt_Transaction>();
        }
    
        public int Mesin_PK { get; set; }
        public int KodeMesin { get; set; }
        public int StatusMesin_FK { get; set; }
        public int Status_FK { get; set; }
    
        public virtual tm_StatusMesin tm_StatusMesin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_Transaction> tt_Transaction { get; set; }
    }
}
