//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_Mesin
    {
        public int Mesin_PK { get; set; }
        public int KodeMesin { get; set; }
        public int StatusMesin_FK { get; set; }
        public int Status_FK { get; set; }
    }
}
