//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_Recorder
    {
        public int Recorder_PK { get; set; }
        public int NoRecorder { get; set; }
        public string NIP { get; set; }
        public string Nama { get; set; }
        public int Status_FK { get; set; }
    }
}
