//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_StatusMesin
    {
        public int StatusMesin_PK { get; set; }
        public string Status { get; set; }
        public double Nilai { get; set; }
        public Nullable<int> Status_FK { get; set; }
    }
}
