//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NETMVCCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_Daily
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_Daily()
        {
            this.tt_Transaction = new HashSet<tt_Transaction>();
        }
    
        public int Daily_PK { get; set; }
        public System.DateTime Date { get; set; }
        public int Recorder_FK { get; set; }
        public string SheetNum { get; set; }
        public int Status_FK { get; set; }
    
        public virtual tm_Recorder tm_Recorder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_Transaction> tt_Transaction { get; set; }
    }
}
